language: cpp

services:
  - docker

sudo: required
dist: trusty
osx_image: xcode10.3

env:
  global:
    - QDEP_CACHE_DIR=$HOME/.qdep-cache
    - QT_VER=5.12.6
    - DOCKER_IMAGE=lts
    - IS_LTS=true
    - NO_TESTS=true
    - LTS_MODS_DESKTOP="qtjsonserializer qtrestclient qtservice qtdatasync qtmvvm qtautoupdater qtapng"  # build qtapng last because it disables the docs
    - LTS_MODS_MOBILE1="qtjsonserializer qtservice qtdatasync"
    - LTS_MODS_MOBILE2="qtrestclient qtmvvm qtapng"
    - LTS_MODS_MOBILE="$LTS_MODS_MOBILE1 $LTS_MODS_MOBILE2"

matrix:
  include:
    - os: linux
      env:
        - PLATFORM=gcc_64
        - LTS_MODS=$LTS_MODS_DESKTOP
        - BUILD_DOC=true
        - BUILD_EXAMPLES=true
    - os: linux
      env:
        - PLATFORM=android_arm64_v8a
        - LTS_MODS=$LTS_MODS_MOBILE
    - os: linux
      env:
        - PLATFORM=android_armv7
        - LTS_MODS=$LTS_MODS_MOBILE
    - os: linux
      env:
        - PLATFORM=android_x86
        - LTS_MODS=$LTS_MODS_MOBILE
    - os: osx
      env:
        - PLATFORM=clang_64
        - LTS_MODS=$LTS_MODS_DESKTOP
    - os: osx
      env:
        - PLATFORM=ios
        - LTS_MODS=$LTS_MODS_MOBILE1
    - os: osx
      env:
        - PLATFORM=ios
        - LTS_MODS=$LTS_MODS_MOBILE2
        - DOWNLOAD_MODS=$LTS_MODS_MOBILE1

before_install:
  - travis_wait 40 ./qtmodules-travis/ci/$TRAVIS_OS_NAME/setup.sh

script:
  - ./travis-build.sh

before_deploy:
  - ./travis-deploy.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: EVJOmAKEPL3iCm8iPpwj5w8bsNK5b8gxKIXKfoLTCZ3Isvezr7ZH5MFWZ2PbItZ+JiKcXtQpp6ZN0xXPLHLzoXtWyqMTtwrZIepyVKjlFW/smcfYiTBuaw6onUGxK6TmQvfi9JSOlX25thF+Hle+XkwcGKS1VzL6qVhx5TSzmsyw7XPb693OkfF69Dj5ImT+Y9gCdIlBReViRELIkm4uV/l4XdSAa2Ig29uh+y5uznTZ7S8kvtVPmukzjQaHaz1LgMtECEJVMksruEC2tSuNUei3O5LOXhMhMLArxsYtkK9SH+P0FcDQUQnVJd+uCyghTKJmOerF4y96Ewnj7PMDvoFpOY9ac8k6BdoREOGOF+x7nS2aFPVgXcu4IfJYOZCqQbIc8sZWNN8VYAZHUBpBwGPKF/nNzGdpCHddKz/XCFKs5C0hsHuqwhXJGzjYLZghUuy+J20fd4V7mdUrslppWlT/MiPyFUrrKb5q9hhlzn9DZinn5o/kzpgMcj8NxdtPhTrF2RqcPEUyXoeW+1VvJX/tTPH1g1e1wMk1eR7TX+Dcj5V0kaCgG0rW0Ki8f8vDTjLWUIE48MXdiBiRQhXwbniesX4ppqOOoY6RA0mamc7asesbCt+AmZxfKM64hML2n+k3K9KfV4gF/qpymWZqNElfugudWE27SwA54Dy1QfY=
  file_glob: true
  file: install/*_*_$QT_VER.tar.xz
  on:
    repo: Skycoder42/QtModules-LTS
    tags: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $QDEP_CACHE_DIR
