image:
  - Visual Studio 2015
  - Visual Studio 2017

version: build-{build}

environment:
  QT_VER: 5.12.4
  IS_LTS: true
  NO_TESTS: true
  LTS_MODS: qtjsonserializer qtrestclient qtservice qtdatasync qtmvvm qtautoupdater qtapng

  matrix:
    - PLATFORM: msvc2017_64
    - PLATFORM: msvc2017
    - PLATFORM: mingw73_64
    - PLATFORM: mingw73_32
    - PLATFORM: winrt_x64_msvc2017
    - PLATFORM: winrt_x86_msvc2017
    - PLATFORM: winrt_armv7_msvc2017
    - PLATFORM: msvc2015_64

matrix:
  exclude:
    - PLATFORM: msvc2017_64
      image: Visual Studio 2015
    - PLATFORM: msvc2017
      image: Visual Studio 2015
    - PLATFORM: mingw73_64
      image: Visual Studio 2015
    - PLATFORM: mingw73_32
      image: Visual Studio 2015
    - PLATFORM: winrt_x64_msvc2017
      image: Visual Studio 2015
    - PLATFORM: winrt_x86_msvc2017
      image: Visual Studio 2015
    - PLATFORM: winrt_armv7_msvc2017
      image: Visual Studio 2015
    - PLATFORM: msvc2015_64
      image: Visual Studio 2017

install:
  - git submodule init
  - git submodule update
  - .\qtmodules-travis\ci\win\setup.bat

build_script:
  - .\appveyor-build.bat

after_build:
  - .\appveyor-deploy.bat

artifacts:
  - path: install\*_*_%QT_VER%.zip

deploy:
  provider: GitHub
  auth_token:
    secure: Cp5GRQku2ZWnKPE12NB5q11ZO0Fr5mlzdUTjnLpYJr/dki4LPVqm231edFggogy8
  artifact: /.*\.zip/
  force_update: false
  on:
    appveyor_repo_tag: true

cache:
 - 'C:\Users\appveyor\AppData\Local\qdep\qdep\Cache -> appveyor.yml'
